# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Recipes Approved by Georgie
email: will@willjackson.uk
description: Here. Find recipes. No spice. No olives. Georgie approves (kind of).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://recipes.willjackson.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: we_jackson
instagram_username: willjackson.uk

# Build settings
# theme: minima 
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Will's changes
site.locale: en-GB
repository: wovenandwoods/recipes.willjackson.uk
logo: "/assets/images/gorgzilla.jpeg"
include: ["_pages"]
title_separator: "|"
teaser: /assets/images/gorgzilla.jpeg
timezone: Europe/London

author:
  name: "Will Jackson"
  avatar: "/assets/images/gorgzilla.jpeg"
  bio: "I am a very extravagant man."
  location: "London, UK"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

defaults:
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/